# Generated by Django 3.1.7 on 2021-04-05 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=50)),
                ('service_description', models.TextField()),
                ('premium', models.BooleanField()),
                ('allocation', models.CharField(max_length=50)),
            ],
        ),
    ]
