# Generated by Django 3.1.7 on 2021-04-05 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('office_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('office_name', models.CharField(max_length=100)),
                ('attribution', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('organization_code', models.IntegerField(primary_key=True, serialize=False)),
                ('organization_name', models.CharField(max_length=200)),
                ('organization_description', models.TextField()),
                ('date_joined', models.DateField()),
                ('address1', models.CharField(max_length=200)),
                ('address2', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=20)),
                ('zipcode', models.CharField(max_length=12)),
                ('phone_number', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionType',
            fields=[
                ('subscription_type_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('subscription_type_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('address1', models.CharField(max_length=100)),
                ('address2', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=25)),
                ('state', models.CharField(max_length=20)),
                ('zip_code', models.CharField(max_length=10)),
                ('employer_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('subscriberID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('request_date', models.DateField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('motif_of_cancellation', models.CharField(max_length=50)),
                ('beneficiaryID', models.CharField(max_length=50)),
                ('service_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.service')),
                ('subscription_type_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.subscriptiontype')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('native_country', models.CharField(max_length=25)),
                ('citizenship', models.CharField(max_length=25)),
                ('is_delegate', models.BooleanField()),
                ('organization_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.organization')),
                ('subscriberID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.subscriber')),
            ],
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('office_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.office')),
                ('subscriberID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.subscriber')),
            ],
        ),
    ]
